### ISSUE TITLE
HACS: Arlo Custom Component broken after reboot. 

### ISSUE THREAD

**Issue by thejeffreystone** [thejeffreystone/home-assistant-configuration#54]
`2020-03-20 15:38:51 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 183, in setup
    hide_deprecated_services=hide_deprecated_services,verbose_debug=verbose_debug)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 67, in __init__
    for device in self._devices:
TypeError: 'NoneType' object is not iterable`

Appears to have already been reported: https://github.com/twrecked/hass-aarlo/issues/190

**Comment by thejeffreystone** [comment]
Looks like pyarlo might be the culprit now...

https://github.com/tchellomello/python-arlo/issues/114

**Comment by thejeffreystone** [comment]
Issue is resolved.
